/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.gestion;

import Controlador.ControladorClientes;
import Exceptions.ClienteYaExisteException;
import GUI.Utiles.Vistas;
import GUI.pantallaPpal;
import gestionPeliculas.dto.Cliente;
import gestionPeliculas.dto.UtilesFecha;
import java.awt.event.KeyEvent;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguelañez-PC
 */
public class AltaCliente extends javax.swing.JDialog {
    pantallaPpal padre;
    /**
     * Creates new form dialogoAlta
     */
    public AltaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        padre = (pantallaPpal) parent;
        cargarAyudaJH();
    }

    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanelInputs = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelNombre2 = new javax.swing.JLabel();
        jLabelNombre3 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jSpinnerFechAlta = new javax.swing.JSpinner();
        jComboBoxProvincia = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabelNIF = new javax.swing.JLabel();
        jTextFieldNIF = new javax.swing.JTextField();
        jLabelError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dar de alta a un usuario....");
        setMinimumSize(new java.awt.Dimension(445, 383));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jKeyReleasedHandlerATRAS(evt);
            }
        });

        jPanelTitulo.setBackground(new java.awt.Color(153, 255, 51));
        jPanelTitulo.setMinimumSize(new java.awt.Dimension(400, 50));
        jPanelTitulo.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Dar de Alta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelTitulo.add(jButton1, java.awt.BorderLayout.LINE_END);

        jButton4.setBackground(new java.awt.Color(153, 204, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("<- Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanelTitulo.add(jButton4, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jPanelTitulo, java.awt.BorderLayout.PAGE_START);

        jPanelInputs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelInputsMouseClicked(evt);
            }
        });
        jPanelInputs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanelInputsKeyReleased(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Dar de Alta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabelNombre.setText("Nombre");

        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imgs/newUser.png"))); // NOI18N
        jLabelFoto.setText("Nuevo user");

        jLabelNombre1.setText("Apellidos");

        jLabelNombre2.setText("Fecha de Alta");

        jLabelNombre3.setText("Provincia");

        jTextFieldNombre.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jTextFieldNombre.setToolTipText("Nombre del usuario...");
        jTextFieldNombre.setActionCommand("<Not Set>");

        jTextFieldApellidos.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jTextFieldApellidos.setToolTipText("Nombre del usuario...");
        jTextFieldApellidos.setActionCommand("<Not Set>");

        jSpinnerFechAlta.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jSpinnerFechAlta.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        jComboBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asturias", "Cantabria", "León" }));

        jButton2.setText("<- Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelNIF.setText("DNI / NIF");

        jTextFieldNIF.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jTextFieldNIF.setToolTipText("Nombre del usuario...");
        jTextFieldNIF.setActionCommand("<Not Set>");

        jLabelError.setForeground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Introduce los datos del nuevo usuario...");

        javax.swing.GroupLayout jPanelInputsLayout = new javax.swing.GroupLayout(jPanelInputs);
        jPanelInputs.setLayout(jPanelInputsLayout);
        jPanelInputsLayout.setHorizontalGroup(
            jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInputsLayout.createSequentialGroup()
                .addGroup(jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInputsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInputsLayout.createSequentialGroup()
                        .addGroup(jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInputsLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldApellidos)
                                    .addComponent(jTextFieldNombre)
                                    .addComponent(jSpinnerFechAlta)
                                    .addComponent(jComboBoxProvincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNIF)))
                            .addGroup(jPanelInputsLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelInputsLayout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)))))
                        .addGap(0, 72, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInputsLayout.setVerticalGroup(
            jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNIF)
                    .addComponent(jTextFieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre2)
                    .addComponent(jSpinnerFechAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre3)
                    .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFoto)
                    .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanelInputs, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Cancelar la edición de la Película?", "Confirmación", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.CANCEL_OPTION) {
            return;
        }
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String DNI = jTextFieldNIF.getText();
        String nombre = jTextFieldNombre.getText();
        String apellidos = jTextFieldApellidos.getText();
        String fecha = UtilesFecha.spinnerFechaToStringDate(jSpinnerFechAlta.getValue());
        String provincia = (String) jComboBoxProvincia.getSelectedItem();
        boolean todoCorrecto = true;
        
        if (DNI.isBlank() || !DNI.matches("[0-9]{8}[A-Z]")) { //Obligamos al usuario a usar un DNI válido
            jLabelError.setText("Introduce un NIF válido!");
            jTextFieldNIF.requestFocusInWindow();
            todoCorrecto = false;
        }
        if (nombre.isBlank()) {
            jLabelError.setText("Escribe el nombre!");
            jTextFieldNombre.requestFocusInWindow();
            todoCorrecto = false;
        }
        if (apellidos.isBlank()) {
            jLabelError.setText("Obligatorio apellidos!");
            jTextFieldApellidos.requestFocusInWindow();
            todoCorrecto = false;
        }
        if (!todoCorrecto) {
            return;
        }
        Cliente nuevo = new Cliente(DNI, nombre, apellidos, fecha, provincia);
        //Actualizar en BBDD con el Controlador
        //boolean hecho = LogicaAppClientes.agregarCliente(nuevo);
        try {
            ControladorClientes.nuevoCliente(nuevo);
        } catch (ClienteYaExisteException yaExisteErr) {
            Vistas.mostrarErrorGUI(rootPane, "DNI YA EN EL SISTEMA!", yaExisteErr.getMessage());
        }
        
        //Cerrar la ventana de Diálogo
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jKeyReleasedHandlerATRAS(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jKeyReleasedHandlerATRAS
        if (evt.getKeyCode() == KeyEvent.VK_V) {
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_jKeyReleasedHandlerATRAS

    private void jPanelInputsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelInputsKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_V) {
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_jPanelInputsKeyReleased

    private void jPanelInputsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInputsMouseClicked
        //Si clicamos en el JPanel de los Campos de Texto (fuera de estos) ó en el JPanel del Campo de Título
        if (evt.getComponent().equals(this.jPanelInputs) || evt.getComponent().equals(this.jPanelTitulo)) {
            //...darle el Foco al elemento al que se ha hecho clic
            evt.getComponent().requestFocusInWindow();
        }
    }//GEN-LAST:event_jPanelInputsMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String DNI = jTextFieldNIF.getText();
        String nombre = jTextFieldNombre.getText();
        String apellidos = jTextFieldApellidos.getText();
        String fecha = UtilesFecha.spinnerFechaToStringDate(jSpinnerFechAlta.getValue());
        String provincia = (String) jComboBoxProvincia.getSelectedItem();
        boolean todoCorrecto = true;
        
        if (DNI.isBlank() || !DNI.matches("[0-9]{8}[A-Z]")) { //Obligamos al usuario a usar un DNI válido
            jLabelError.setText("Introduce un NIF válido!");
            jTextFieldNIF.requestFocusInWindow();
            todoCorrecto = false;
        }
        if (nombre.isBlank()) {
            jLabelError.setText("Escribe el nombre!");
            jTextFieldNombre.requestFocusInWindow();
            todoCorrecto = false;
        }
        if (apellidos.isBlank()) {
            jLabelError.setText("Obligatorio apellidos!");
            jTextFieldApellidos.requestFocusInWindow();
            todoCorrecto = false;
        }
        if (!todoCorrecto) {
            return;
        }
        Cliente nuevo = new Cliente(DNI, nombre, apellidos, fecha, provincia);
        //Actualizar en BBDD con el Controlador
        //boolean hecho = LogicaAppClientes.agregarCliente(nuevo);
        try {
            ControladorClientes.nuevoCliente(nuevo);
        } catch (ClienteYaExisteException yaExisteErr) {
            Vistas.mostrarErrorGUI(rootPane, "DNI YA EN EL SISTEMA!", yaExisteErr.getMessage());
        }
        
        //Cerrar la ventana de Diálogo
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Cancelar la creación del Usuario?", "Confirmación", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.CANCEL_OPTION) {
            return;
        }
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AltaCliente dialog = new AltaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    /**
     * Habilitará el acceso a la ayuda de JavaHelp para esta ventana de la aplicación.
     */
    private void cargarAyudaJH() {
        try {
            // Carga el fichero de ayuda
            File fichero = new File("src" + File.separator + "help" + File.separator + "help.hs");
            URL hsURL = fichero.toURI().toURL();

            // Crea el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            // Activar la ayuda para cada elemento que deseemos que la tenga asociada
            hb.enableHelpKey(this.getContentPane(), "ayudaClienteAlta", helpset); //abrirá la ayuda para getión de Películas
        } catch (HelpSetException hsExc) {
            System.err.println(hsExc.getMessage());
        } catch (MalformedURLException urlErr) {
            System.err.println("Formato de URL incorrecto!");
            System.err.println(urlErr.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBoxProvincia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelNombre3;
    private javax.swing.JPanel jPanelInputs;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JSpinner jSpinnerFechAlta;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldNIF;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
