/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.gestion;

import Controlador.ControladorPeliculas;
import Exceptions.PeliculaYaExisteException;
import GUI.Utiles.Vistas;
import GUI.pantallaPpal;
import gestionPeliculas.dto.Pelicula;
import gestionPeliculas.dto.UtilesFecha;
import gui_eventospersonalizado.ImagenFondo2;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Date;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguelañez-PC
 */
public class NuevaPelicula extends javax.swing.JDialog {

    ImagenFondo2 imgFondo2;
    pantallaPpal padre;
    /**
     * Creates new form NuevaPelicula
     */
    public NuevaPelicula(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabelError.setVisible(false);
        prepararCompPersonalizado();
        padre = (pantallaPpal) parent;
        this.setLocationRelativeTo(null); //centrar la ventana en pantalla
        cargarAyudaJH();
    }
    
    /**
     * Creates new form NuevaPelicula
     */
    public NuevaPelicula(java.awt.Frame parent, boolean modal, String tituloPelicula) {
        super(parent, modal);
        initComponents();
        this.jTFTitulo.setText(tituloPelicula);
        jLabelError.setVisible(false);
        prepararCompPersonalizado();
        padre = (pantallaPpal) parent;
        this.setLocationRelativeTo(null); //centrar la ventana en pantalla
        cargarAyudaJH();
    }

    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jButtonVolver = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jTFTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerAnno = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerFechaEm = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabelHintImagen = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jPanelImagenFondoArrastable1 = new gui_eventospersonalizado.JPanelImagenFondoArrastable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear nueva Pelicula...");
        setMinimumSize(new java.awt.Dimension(404, 300));

        jPanelTitulo.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanelTitulo.setMinimumSize(new java.awt.Dimension(225, 30));
        jPanelTitulo.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanelTitulo.setLayout(new java.awt.GridLayout(1, 0));

        jButtonVolver.setText("<-Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanelTitulo.add(jButtonVolver);

        jLabelError.setForeground(new java.awt.Color(255, 102, 102));
        jLabelError.setText("La película ya Existe!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabelError)
                .addContainerGap())
        );

        jPanelTitulo.add(jPanel3);

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 3, 14)); // NOI18N
        jLabel1.setText("NUEVA PELICULA");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanelTitulo.add(jLabel1);

        getContentPane().add(jPanelTitulo, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabelTitulo.setText("Titulo Pelicula");

        jTFTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFTituloFocusLost(evt);
            }
        });
        jTFTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFTituloKeyReleased(evt);
            }
        });

        jLabel2.setText("Fecha Emision");

        jSpinnerAnno.setModel(new javax.swing.SpinnerNumberModel(2000, 1700, 2030, 1));

        jLabel3.setText("Anio");

        jSpinnerFechaEm.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(1893538020000L), java.util.Calendar.DAY_OF_MONTH));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("CONFIRMAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelHintImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHintImagen.setText("Imagen Pelicula");

        jLabel4.setText("Genero");

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción", "Aventura", "Ciencia Ficción", "Fantasía", "Drama", "Psicológica", "Suspense" }));

        jPanelImagenFondoArrastable1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 204, 255), new java.awt.Color(102, 102, 102)));
        jPanelImagenFondoArrastable1.setToolTipText("DOBLE CLIC para Editar! ARRASTRA para descartar!");

        javax.swing.GroupLayout jPanelImagenFondoArrastable1Layout = new javax.swing.GroupLayout(jPanelImagenFondoArrastable1);
        jPanelImagenFondoArrastable1.setLayout(jPanelImagenFondoArrastable1Layout);
        jPanelImagenFondoArrastable1Layout.setHorizontalGroup(
            jPanelImagenFondoArrastable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );
        jPanelImagenFondoArrastable1Layout.setVerticalGroup(
            jPanelImagenFondoArrastable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTFTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jSpinnerAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jSpinnerFechaEm, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabelHintImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelImagenFondoArrastable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerFechaEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelHintImagen)
                        .addGap(4, 4, 4)
                        .addComponent(jPanelImagenFondoArrastable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(8, 8, 8))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Cancelar la creación de la película?", "Cancelar", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            this.dispose();
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonVolverActionPerformed

    public void prepararCompPersonalizado() {
        this.imgFondo2 = new ImagenFondo2(new File("src/GUI/imgs/placeholder-img.png").getAbsoluteFile(), 1.0f);
        this.jPanelImagenFondoArrastable1.addArrastreListener(
        new gui_eventospersonalizado.ArrastreListener() {
            //Si arrastramos, preguntar si descartar la imágen.
            @Override
            public void arrastre() {
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                if (JOptionPane.showConfirmDialog(rootPane, "¿Seguro que desea descartar la imágen seleccionada?", "Eliminar imágen", JOptionPane.WARNING_MESSAGE) == JOptionPane.OK_OPTION) {
                    imgFondo2 = new ImagenFondo2(new File("src/GUI/imgs/placeholder-img.png").getAbsoluteFile(), 1.0f);
                    jPanelImagenFondoArrastable1.setFondoImg(imgFondo2);
                    jPanelImagenFondoArrastable1.repaint();
                }
            }

            //Si hacemos doble clic, mostrar el diálogo para cambiar de imágen y hacerlo si aceptamos.
            @Override
            public void toggleDblClick() {
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                JFileChooser elegirFicherosWindow = new JFileChooser();
                int resultado = elegirFicherosWindow.showOpenDialog(NuevaPelicula.this);

                if (resultado == JFileChooser.APPROVE_OPTION) {
                    //Al aceptar, cambiar el texto de la ruta por la ruta elegida
                    File ficheroTmp = elegirFicherosWindow.getSelectedFile();
                    imgFondo2 = new ImagenFondo2(ficheroTmp.getAbsoluteFile(), 1.0f);
                    jPanelImagenFondoArrastable1.setFondoImg(imgFondo2);
                }
                if (resultado == JFileChooser.CANCEL_OPTION) {
                    //No hacer nada al cancelar
                }
            }
        });
    }
    private void jTFTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFTituloKeyReleased
        
    }//GEN-LAST:event_jTFTituloKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //TODO -> CREAR PELICULA EN BBDD
        String titulo = this.jTFTitulo.getText();
        int anio = Integer.parseInt(this.jSpinnerAnno.getValue().toString());
        String fechaEmision = UtilesFecha.spinnerFechaToStringDate(
                this.jSpinnerFechaEm.getValue());
        Date fechaDateEmision = UtilesFecha.fechaStrToDate(fechaEmision);
        String genero = this.jComboBoxGenero.getSelectedItem().toString();
        //String rutaImg = this.customJLabelImagenPeli.getImgRoot();
        
        //Si la fecha actual ya ha sobrepasado la fecha de emisión que hemos puesto, avisar al Usuario
        if (new Date().after(fechaDateEmision)) {
            Vistas.mostrarErrorGUI(rootPane, "FECHA NO VÁLIDA!", "La fecha de emisión que ha introducido para la película YA HA EXPIRADO! Introduzca una fecha posterior válida");
            return;
        }
        if (ControladorPeliculas.existePelicula(titulo, anio)) {
            Vistas.mostrarErrorGUI(rootPane, "PELÍCULA IDÉNTICA YA GUARDADA", "La película del año que ha intentado\n"
                    + " ingresar ya se encuntra en el Sistema."
                    + "Cambie los datos e inténtelo de nuevo...");
            return;
        }
        Pelicula pelicula = new Pelicula(0, titulo, genero, fechaEmision, anio);
        try {
            ControladorPeliculas.agregarPelicula(pelicula);
        } catch (PeliculaYaExisteException peliYaExisteErr) {
            JOptionPane.showMessageDialog(rootPane, peliYaExisteErr.getMessage(), "LA PEL�?CULA YA EXISTE!", JOptionPane.ERROR_MESSAGE);
        }
        
        //Actualizar la tabla de películas, y recargar la página
        padre.actualizarListaESTRENOS();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Al perder el FOCO, verificar si ya existe una película con el titulo introducido.
     * Si existe, mostrar el JLabel de Error
     * @param evt 
     */
    private void jTFTituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFTituloFocusLost
        if (jTFTitulo.getText().isBlank() || jTFTitulo.getText().isBlank()) {
            jLabelError.setVisible(false);
            return;
        }
        //Sólo hacer aparecer el mensaje de error si existe una película con el titulo establecido.
        if (ControladorPeliculas.getPeliculaByTitulo(jTFTitulo.getText()) != null) {
            jLabelError.setVisible(true);
            return;
        }
        jLabelError.setVisible(false);
    }//GEN-LAST:event_jTFTituloFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevaPelicula dialog = new NuevaPelicula(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    /**
     * Habilitará el acceso a la ayuda de JavaHelp para esta ventana de la aplicación.
     */
    private void cargarAyudaJH() {
        try {
            // Carga el fichero de ayuda
            File fichero = new File("src" + File.separator + "help" + File.separator + "help.hs");
            URL hsURL = fichero.toURI().toURL();

            // Crea el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            // Activar la ayuda para cada elemento que deseemos que la tenga asociada
            hb.enableHelpKey(this.getContentPane(), "ayudaPeliculaAlta", helpset); //abrirá la ayuda para getión de Películas
        } catch (HelpSetException hsExc) {
            System.err.println(hsExc.getMessage());
        } catch (MalformedURLException urlErr) {
            System.err.println("Formato de URL incorrecto!");
            System.err.println(urlErr.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelHintImagen;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private gui_eventospersonalizado.JPanelImagenFondoArrastable jPanelImagenFondoArrastable1;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JSpinner jSpinnerAnno;
    private javax.swing.JSpinner jSpinnerFechaEm;
    private javax.swing.JTextField jTFTitulo;
    // End of variables declaration//GEN-END:variables
}
