/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Controlador.CFG_APP;
import GUI.Utiles.Vistas;
import clienteapi.AuthAPIUtils;
import gestionPeliculas.dto.Cliente;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.net.MalformedURLException;
import java.net.NetworkInterface;
import java.net.URL;
import java.util.Enumeration;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *  TODO --> Cambiar este pseudo-login por el sistema real
 * 
 * @author Miguelañez-PC
 */
public class LoginPrincipal extends javax.swing.JFrame implements CFG_APP {

    
    /**
     * Creates new form LoginPrincipal
     */
    public LoginPrincipal() {
        initComponents();
        cargarAyudaJH(); //Cargar la ayuda de JavaHelp.
        cargarImagenLogo();
        this.setLocationRelativeTo(null); //Centrar la ventana
        this.jMayusc.setVisible(false);
        
        //Cambiar el icono de la aplicación
        try {
            this.setIconImage(ImageIO.read(new File(ICONO_APP).getAbsoluteFile()));
        } catch (IOException errIO) {
            System.err.println("ERROR AL MOSTRAR EL ICONO DE LA APP");
            errIO.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelPW = new javax.swing.JLabel();
        jTextNombreUsuario = new javax.swing.JTextField();
        jPasswordFieldPW = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        labelIMG = new javax.swing.JLabel();
        jMayusc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Peliculeo! Desktop");
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Source Code Pro Black", 0, 36)); // NOI18N
        jButton1.setText("INGRESAR");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 102, 255), new java.awt.Color(102, 102, 255), new java.awt.Color(255, 51, 102), new java.awt.Color(255, 51, 51))));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setLabelFor(jTextNombreUsuario);
        jLabel1.setText("NIF Usuario");

        jLabelPW.setLabelFor(jPasswordFieldPW);
        jLabelPW.setText("Password");

        jTextNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextNombreUsuario.setText("admin");
        jTextNombreUsuario.setToolTipText("");
        jTextNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNombreUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextNombreUsuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreUsuarioKeyTyped(evt);
            }
        });

        jPasswordFieldPW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldPWKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Source Serif Pro", 0, 12)); // NOI18N
        jLabel2.setText("F1 - Ayuda");
        jLabel2.setToolTipText("");
        jLabel2.setEnabled(false);

        jMayusc.setText("! MÁYUS. ACTIVADAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldPW))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMayusc))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(labelIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextNombreUsuario)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPW, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPasswordFieldPW, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jMayusc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ingresar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordFieldPWKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldPWKeyReleased
        switch(evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                ingresar();
                break;
            case KeyEvent.VK_CAPS_LOCK:
                jMayusc.setVisible(!jMayusc.isVisible());
            default:
                break;
        }
    }//GEN-LAST:event_jPasswordFieldPWKeyReleased

    private void jTextNombreUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreUsuarioKeyReleased
        switch(evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                ingresar();
                break;
            case KeyEvent.VK_CAPS_LOCK:
                jMayusc.setVisible(!jMayusc.isVisible());
            default:
                break;
        }
    }//GEN-LAST:event_jTextNombreUsuarioKeyReleased

    private void jTextNombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreUsuarioKeyTyped
        // Evitar que se pueda escribir más allá de 75 caracteres (por seguridad)
        if (jTextNombreUsuario.getText().length() <= 74) {
            return;
        }
        evt.consume();
    }//GEN-LAST:event_jTextNombreUsuarioKeyTyped

    private void jTextNombreUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreUsuarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreUsuarioKeyPressed

    public void ingresar() {
        String tfNombreUser = jTextNombreUsuario.getText();
        char[] PW = jPasswordFieldPW.getPassword();
        if (tfNombreUser.equals("admin") && new String(PW).equals(PASSWORD_ADMIN)) {
            System.out.println("Ingresado al Sistema correctamente!");
            pantallaPpal ventanaPrincipal = new pantallaPpal();
            ventanaPrincipal.setVisible(true);
            this.dispose();
            this.setVisible(false);
        } else {
            Cliente c = new Cliente();
            c.setDNI(tfNombreUser);
            c.setPassword(new String(PW));
            try {
                String res = AuthAPIUtils.sendLoginRequest(c);
                
                if (res.toUpperCase().contains("FALL")) {
                    Vistas.mostrarErrorGUI(rootPane, "ERROR al ingresar!", "Contraseña incorrecta!");
                    return;
                }
                System.out.println("Ingresado al Sistema correctamente!");
                pantallaPpal ventanaPrincipal = new pantallaPpal();
                ventanaPrincipal.setVisible(true);
                this.dispose();
                this.setVisible(false);
            } catch (Exception ioe) {
                JOptionPane.showMessageDialog(rootPane, ioe.getMessage());
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPrincipal().setVisible(true);
            }
        });
    }
    
    /**
     * Habilitará el acceso a la ayuda de JavaHelp para esta ventana de la aplicación.
     */
    private void cargarAyudaJH() {
        try {
            // Carga el fichero de 'script' de ayuda (help.hs)
            File fichero = new File("src" + File.separator + "help" + File.separator + "help.hs");
            URL hsURL = fichero.toURI().toURL();

            // Crea el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            // Activar la ayuda para cada elemento que deseemos que la tenga asociada
            hb.enableHelpKey(this.getContentPane(), "manual", helpset); //panel con el foco default
        } catch (HelpSetException hsExc) {
            System.err.println(hsExc.getMessage());
        } catch (MalformedURLException urlErr) {
            System.err.println("Formato de URL incorrecto!");
            System.err.println(urlErr.getMessage());
        }
    }
    
    /**
     * Recogerá una imágen desde la ruta por defecto, y renderizará la imágen aprovechando el JLabel que hay en pantalla.
     * 
     * Para esto, se aprovecha la clase ImageIO y BufferedImage del paquete Javax y Java.awt
     */
    private void cargarImagenLogo() {
        try {
            BufferedImage bfImg = ImageIO.read(new File(RUTA_IMG));
            this.labelIMG.setSize(labelIMG.getWidth(), labelIMG.getHeight() + 20);
            // Escalar la imagen para que se ajuste al JLabel
            Image imgEscalada = bfImg.getScaledInstance(labelIMG.getWidth(), labelIMG.getHeight(), Image.SCALE_SMOOTH);
            this.labelIMG.setIcon(new ImageIcon(imgEscalada));
        } catch (IOException ioe) {
            Vistas.mostrarErrorGUI(rootPane, "ERROR al cargar la imágen de Logotipo", ioe.getMessage());
        }
        
        //printInetAddress();
    }
    
    public void printInetAddress() {
        try {
        Enumeration lista = NetworkInterface.getNetworkInterfaces();
            while(lista.hasMoreElements()) {
                NetworkInterface nint = (NetworkInterface) lista.nextElement();
                Enumeration<InetAddress> inetAddresses = nint.getInetAddresses();
                if (nint.getName().contains("wlan")) {
                    while (inetAddresses.hasMoreElements()) {
                    InetAddress inetAddress = inetAddresses.nextElement();
                        // Ignore loopback and non-site-local addresses (ensures it's from Wi-Fi or Ethernet)
                        if (!inetAddress.isLoopbackAddress() && inetAddress.isSiteLocalAddress()) {
                            System.out.println(inetAddress.toString().substring(1, inetAddress.toString().length()));
                        }
                    }
                }
                //System.out.println(ipaddr + " - " + nint.getDisplayName());
            }
        } catch (Exception unk) {
            System.out.println(unk.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPW;
    private javax.swing.JLabel jMayusc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldPW;
    private javax.swing.JTextField jTextNombreUsuario;
    private javax.swing.JLabel labelIMG;
    // End of variables declaration//GEN-END:variables

    
}
